### ISSUE TITLE
Elements show "<Loading>" the first time the addon is opened in a session

### ISSUE THREAD

**Issue by xaelophorus** [davidmeen/TomeOfTeleportation#11]
The first time opening the addon in a session, most/all items show as `<Loading>`. Closing and reopening the addon fixes the issue. Example at the link below.

LEFT: Opening addon for the first time in the session. RIGHT: After closing and reopening the addon.
https://imgur.com/a/hZYEAcX

After switching to a different character and then returning to the first:
https://imgur.com/a/9HndL0D

**Comment by davidmeen** [comment]
Should be fixed in 4.1.
