### ISSUE TITLE
Suggestion: Add Hero's Path Shadowlands Teleports

### ISSUE THREAD

**Issue by JamieTundra** [davidmeen/TomeOfTeleportation#13]
Add Hero's Path Shadowlands Dungeon Teleports. These were added in 9.1 and would be a great addition to an already brilliant addon.

**Comment by davidmeen** [comment]
The spells don't seem to be in Wowhead's database, I'll addthem when I find the spell IDs.

**Comment by JamieTundra** [comment]
> The spells don't seem to be in Wowhead's database, I'll addthem when I find the spell IDs.

I unlocked them yesterday so can provide them
220
![image](https://user-images.githubusercontent.com/32909452/124369743-1bbc4e80-dc67-11eb-988f-3a5e56afde32.png)
Necrotic Wake - 354462
![image](https://user-images.githubusercontent.com/32909452/124369747-2e368800-dc67-11eb-9316-a4e0d076ca2f.png)
Plaguefall - 354363
![image](https://user-images.githubusercontent.com/32909452/124369755-41e1ee80-dc67-11eb-950a-fed8ae9a7ec5.png)
Mists - 354464
![image](https://user-images.githubusercontent.com/32909452/124369763-50c8a100-dc67-11eb-9a5e-b5695d2cdc0e.png)
Halls of Atonement - 354465
![image](https://user-images.githubusercontent.com/32909452/124369766-5aea9f80-dc67-11eb-93c4-b100b47861fa.png)
Spires - 354466
![image](https://user-images.githubusercontent.com/32909452/124369768-68078e80-dc67-11eb-8422-e8f2dd95fa9e.png)
Theatre of Pain - 354467
![image](https://user-images.githubusercontent.com/32909452/124369778-7e154f00-dc67-11eb-8151-c063fe1c6f52.png)
De Other Side - 354468
![image](https://user-images.githubusercontent.com/32909452/124369780-87062080-dc67-11eb-81d5-6ed7081565f8.png)
Sanguine Depths - 354469
![image](https://user-images.githubusercontent.com/32909452/124369782-8ff6f200-dc67-11eb-92a1-98c916d37407.png)

**Comment by davidmeen** [comment]
Done.
