### ISSUE TITLE
Missing Morqut Hearth Totem

### ISSUE THREAD

**Issue by Machou** [davidmeen/TomeOfTeleportation#22]
Hi

Can you add this item : [Morqut Hearth Totem](https://www.wowhead.com/item=204481)

> Morqut Hearth Totem
> **Use: Teleports the caster to Morqut Village. Must be within the Forbidden Reach to activate.**
> _"Not all tuskarr who wander off exploring are lost."_

**Comment by davidmeen** [comment]
Added in 4.7.1.
