### ISSUE TITLE
DF Season 2 Dungeon Portals Not Showing?

### ISSUE THREAD

**Issue by mavrck48** [davidmeen/TomeOfTeleportation#25]
I just got the Neltharion's Lair DF S2 dungeon portal (Path of the Earth-Warder) and it is not showing up in the tome of teleportation addon.

![WoWScrnShot_051923_204339](https://github.com/davidmeen/TomeOfTeleportation/assets/6274083/022b99d3-9a35-4f4f-8663-89ab662b66d5)

**Comment by davidmeen** [comment]
Fixed in the latest version.
