### ISSUE TITLE
label:enhancement UI changes maybe :D

### ISSUE THREAD

**Issue by Booggg** [davidmeen/TomeOfTeleportation#26]
I really love this addon! And chance of a UI update /tweek to make it more user friendly. Thanks. Sadly I have no addon knowldge to help.

Few things I've thought of such as:

It looks really dated 
Not having a repeat of the zones tp destinations (eg stormwind) if it wraps onto a new column. 
More distinct colour for the zone names.
Easier way to sort the tps such as drag/drop to reorder. Clicking the up and down arrows to rearange every teleport is really unwieldy.
Different layout than the 5 down columns we have right now and more flexability with size or buttons ect. 
Its hard to see if a spell is enabled or disabled with the small shade of grey used atm.

**Comment by davidmeen** [comment]
Settings have been reworked in 5.0 so most of these suggestions can now be set up.
