### ISSUE TITLE
Setting to auto exit shapeshifts

### ISSUE THREAD

**Issue by ZehelFenris** [davidmeen/TomeOfTeleportation#30]
I recently changed to play my druid a lot and keep forgetting to exit shapeshift and get the error message "Can't use that ability while pacified" I was wondering if you could add a setting to auto exit shapeshift as soon as any teleports is clicked.

**Comment by davidmeen** [comment]
I've tried to do this, but the game doesn't let you cancel a form and cast a spell in a single click.
