### ISSUE TITLE
Guild cloaks not equipping correctly

### ISSUE THREAD

**Issue by mdavidson37** [davidmeen/TomeOfTeleportation#36]
When trying to use the guild cloaks I get a "This Item cannot be Equipped in this Slot" error.

This occurs both when trying to equip and after use.

After playing about a bit it appears that blizzard has reversed the change that this workaround was addressing: https://github.com/davidmeen/TomeOfTeleportation/commit/c3b6e39b52d2060bf1315fdf12109524d424d3cd

**Comment by davidmeen** [comment]
Fixed in 4.12.3
