### ISSUE TITLE
"Path of the Nightmare Lord" dungeon TP is ignoring filter settings 

### ISSUE THREAD

**Issue by Booggg** [davidmeen/TomeOfTeleportation#42]
Hi. Amazing update! Thanks.

"Path of the Nightmare Lord" is ignoring Dungeon filter settings (hide dungeon spells, current dungeons only ect)

**Comment by davidmeen** [comment]
I can't reproduce this. Are any other dungeons affected?

**Comment by Booggg** [comment]
No, just this one. Maybe I can delete it or reset this one and see if it fixes it.

**Comment by Booggg** [comment]
https://cdn.discordapp.com/attachments/654425579734433800/1235266350511816735/World_Of_Warcraft_2024.05.01_-_17.27.08.03.mp4?ex=6633bef0&is=66326d70&hm=ae208ca2fd67b96ecb971e5fe80351532aad5eceedc9a5b7e00f9b2ab95ea3a9&

clip of it

**Comment by Booggg** [comment]
N
