### ISSUE TITLE
Request: Text Alignment on Buttons

### ISSUE THREAD

**Issue by nancikennedy** [davidmeen/TomeOfTeleportation#45]
Request: Make the vertical centers of the text/icon align by default. If this is impossible because of a Blizz limitation, aligning their bottom edges would be the second choice.

This is a very small niggle for most people, but for people with visual issues (for me dyslexia) the way the alignment currently seems to work (bottom of text/center of icon, vertically) can be an irritant.

**Comment by davidmeen** [comment]
I've modified the alignment so text is verticaly centred with the icon. let me know if that isn't what you wanted.

**Comment by nancikennedy** [comment]
You have made the OCD/dyslexic me so very happy! Thanks for taking the time to address such a (usually) trivial request. :)
