### ISSUE TITLE
Request: Upload addon to Wago Addon Manager

### ISSUE THREAD

**Issue by Feedy88** [davidmeen/TomeOfTeleportation#47]
Hi @davidmeen,

I really enjoy your addon and am actively using it. I know that your addon is alredy listed on Curseforge but noticed, the Wago Client does not recognize your addon. Would you consider it listing there as well?

If you don't like to list it, would an option be that I create a fork and list it with all credit attributed to you?

Thanks.

**Comment by davidmeen** [comment]
Does this not work? https://addons.wago.io/addons/tomeofteleportation. I've not tested with an addon manager.

**Comment by Feedy88** [comment]
In fact it works perfectly fine, thanks for pointing out. I have no clue why the Wago App didn't recognize it from the Addons Folder. Closing Bug.
