### ISSUE TITLE
Class Teleports don't work

### ISSUE THREAD

**Issue by joeyherne** [davidmeen/TomeOfTeleportation#50]
Can't get any class teleports (Astral Recall, monk tele etc) to show up in addon.

**Comment by davidmeen** [comment]
I've tried multiple characters but the spells show up on all of them. Try this:
Open interface options.
Go to the addons tab.
Press the + next to Tome of Teleportation and select Customize Teleporters.
Press View Spell List.
Change the spell to Always Show.

If that doesn't work, delete the file [Install folder]\_retail_\WTF\Account\youraccountname\SavedVariables\TomeOfTeleportation.lua.

**Comment by joeyherne** [comment]
Deleting the file worked, thank you.

**Comment by davidmeen** [comment]
The next version will have a button to reset all settings to fix issues like this.
