### ISSUE TITLE
Request: API to open Tome of Teleportation outside the AddOn

### ISSUE THREAD

**Issue by Toxicom** [davidmeen/TomeOfTeleportation#51]
# Description
Hello, I am Toxi from ToxiUI and have received a request to integrate Tome of Teleportation in to my AddOn, see https://github.com/Toxicom/toxiui/issues/113

Basically I would call a function to open Tome of Teleportation from inside my AddOn, but after looking through your code, I can't find a function that I could call.

Could you please add a way for other addons to open Tome of Teleportation, or if a method already exists direct me to it?

# Acceptance criteria
- [ ] Tome of Teleportation can be opened by other AddOns

**Comment by davidmeen** [comment]
Try TeleporterSlashCmdFunction()

**Comment by Toxicom** [comment]
That works, thank you

**Comment by Toxicom** [comment]
Sorry, reopening the issue. Could you introduce a toggle function for the teleporter? That seems like a standard for all the WoW API frames.
```lua
function TeleporterToggle()
  if isVisible then
    TeleporterClose()
  else
    TeleporterOpenFrame()
  end
end
```

**Comment by davidmeen** [comment]
You can use TeleporterSlashCmdFunction() to do that.
