### ISSUE TITLE
tome of town portal

### ISSUE THREAD

**Issue by JarfJarfBinks** [davidmeen/TomeOfTeleportation#52]
this is on a seperate cd then a hearthstone, can this be displayed abiove hearthstones if known, so basically it would be first then hearthstone, that is on the seperate cd

**Comment by davidmeen** [comment]
Hearthstones with a separate cooldown are now displayed under the others (like Astral Recall always has).

**Comment by JarfJarfBinks** [comment]
I found 3 toys that share the cd, someone said the hearth from hearthstones 10th anniversary does also, but I do not have that one
![Screenshot 2024-09-09 135454](https://github.com/user-attachments/assets/74dc8caa-b047-4acb-875f-19ad5fab7de8)
this show my 15 min and 30 min ones

also, ty for the response and fix :D
